name: Common Lisp CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Builds the Docker image using the Dockerfile in the repository.
      # We tag the image so we can refer to it in later steps.
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag cl-freelock-app:latest
      - name: Run tests
        run: docker run --rm cl-freelock-app:latest
      # We override the default command to run the 'benchmark' target.
      - name: Run benchmarks
        run: docker run --rm cl-freelock-app:latest make benchmark
