# Here I'm going to just use the same docker setup (minus jenkins) as the SBCL.yml, have it pull the dockerfile supplied by the clasp devs, and then have it run the test suite via clasp.
# I did think about adding it into the original yml, however, that would take up more time, and would be an issue regarding seperation of concerns. We will instead rely on github matrix.

# docker pull ghcr.io/clasp-developers/clasp:latest

#I could also have clasp be pulled as a base image, which I haven't decided on yet, but I'll start with the git pull first.

# I would like to use roswell to install clasp, but currently the support for clasp is a little bit lackluster.


# REMINDER: I need to add a status badge for SBCL and CLASP to the Readme.md file.

# If needed for keyring issues:
# rm -rf /etc/pacman.d/gnupg ...then... pacman -S archlinux-keyring --noconfirm ...then... pacman-key --populate archlinux
# The current image from clasp has old keyrings, so patches like this might be...
# needed. Right now we're fine, but it's written here just for reference.

#-----------------------------------------------------------------------
#
#                   This whole file needs changed
#
#-----------------------------------------------------------------------
name: CLASP

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  setup-and-test-CLASP:
    runs-on: ubuntu-24.04
    # ubuntu-latest is mutable. Additionally, 24.04 LTS has the most security features.
    # Though, latest currently points to this version, but it's still better not to use the latest tag.

    # using the :latest mutable tag with no digest pinning is insecure. (CWE-829, CWE-494)
    # :latest is mutable. Additionally, latest can change at any time.
    # We need to pin the digest. 
    # Actually ghcr.io/clasp-developers/clasp is stale. Three years old, no version control, latest tag, and old keyrings, so for no we will use something else.
    # We're actually not even going to use docker. IF we want reproducibility, then NIX is better.
    # However, hermeticity (especially at the extent of nix), also means that our tests run in a pristine environment that real users may never have.
    # So we will need to have both: hermetic tests, and integration tests.

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Refresh keys
        run: pacman-key --refresh-keys
        # If ever needed, we can also add pacman-key --init and pacman-key --populate archlinux
      - name: Disable pacman 7 sandbox
        run: sed -i 's/^#DisableSandbox/DisableSandbox/' /etc/pacman.conf
# I tried having it run pacman -Syu --noconfirm, but clasp needs particular versions of things like clang and llvm, so it's best not to use Syu in this case.
      - name: Install environment packages
        run: |
          echo "Running ldd on clasp for debug logs..."
          ldd $(which clasp)
      - name: Install qlot with curl
        run: curl -L https://qlot.tech/installer | sh # This is actually the most insecure part of this CI/CD. (CWE-829, CWE-494) and NO pinning.
      
      - name: qlot init check
        run: qlot init

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make test
      
      - name: Run benchmarks
        run: echo "Benchmarks are not yet compatible with CLASP." #make benchmark

# PATHS:
# qlot via curl will be installed at /usr/local/bin/qlot
