name: qlfile-cron

on:
  schedule:
    - cron: '20/15 * * * *'
    # '0 5 * * 5'

jobs:
  setup-and-check-dep-compatability:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag cl-freelock-app:latest
        
      - name: Remove qlfile.lock
        run: docker run --rm cl-freelock-app:latest rm qlfile.lock

      - name: Remake qlfile.lock
        run: docker run --rm cl-freelock-app:latest qlot install 

      - name: Run tests
        run: docker run --rm cl-freelock-app:latest
      # We override the default command to run the 'benchmark' target.
      - name: Run benchmarks
        run: docker run --rm cl-freelock-app:latest make benchmark

# PATHS:
# qlot via ros install will be installed at .roswell/bin
