name: vale-linting

on:
  push:
    branches: [ gh-pages ]
  
jobs:
  setup-vale:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vale-cli/vale-action@v2
        with:
          files: docs/index.html