name: vale-linting

on:
  push:
    branches: [ gh-pages ]
  
jobs:
  setup-vale:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        run: actions/checkout@v4
      
      - name: setup-vale-CLI
        uses: vale-cli/vale-action@v2
        with:
          files: docs/
          fail_on_error: true
          filter_mode: file