name: vale-linting

on:
  push:
    branches: [ gh-pages ]
  
jobs:
  setup-vale:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vale-cli/vale-action@v2
        with:
          files: docs/index.html
          reporter: github-check
          # fail_on_error: true -- I'm commenting this out for now until I can figure out how to add exceptions to spelling checks.